name: Prettier & Eslint

on: [pull_request]

env:
  YARN_CACHE_FOLDER: .cache/yarn

jobs:
  prettier-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.{ts,tsx,js,jsx,json}
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: echo '${{ toJSON(steps.setup_node_id.outputs) }}'
      - if: ${{ steps.setup_node_id.outputs.cache-hit != 'true' }}
        run: yarn install
      - run: yarn format:ci
      - run: yarn lint:ci
